=== sentora/sentora-core/etc/apps/phpsysinfo/language/translation.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!-- $Id: translation.xsd 150 2009-03-20 20:19:23Z bigmichi1 $ -->
<schema targetNamespace="http://phpsysinfo.sourceforge.net/translation"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation" xmlns="http://www.w3.org/2001/XMLSchema">
  <complexType name="translationType">
    <sequence>
      <element name="expression" type="tns:expressionType" maxOccurs="unbounded"
        minOccurs="93">
      </element>
    </sequence>
    <attribute name="charset" type="string" use="required"></attribute>
    <attribute name="language" type="string" use="required"></attribute>
  </complexType>
  <complexType name="expressionType">
    <sequence>
      <element name="exp" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="id" use="required">
      <simpleType>
        <restriction base="string">
          <length value="3"></length>
          <pattern value="\d\d\d"></pattern>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="name" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+"></pattern>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>
  <element name="translation" type="tns:translationType"></element>
</schema>

=== sentora/sentora-core/etc/apps/phpsysinfo/language/tw.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: tw.xml 699 2012-09-15 11:57:13Z namiltd $ -->
<!--
phpSysInfo language file Language: Chinese Traditional Created by: capriskye::andrew@openlyu.com http://openlyu.com/
-->
<tns:translation language="chinese_big5" charset="utf-8"
 xmlns:tns="http://phpsysinfo.sourceforge.net/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation translation.xsd">
  <expression id="001" name="title">
    <exp>系統資料</exp>
  </expression>
  <expression id="002" name="vitals">
    <exp>主要資料</exp>
  </expression>
  <expression id="003" name="hostname">
    <exp>主機名稱</exp>
  </expression>
  <expression id="004" name="ip">
    <exp>連線 IP (Listen)</exp>
  </expression>
  <expression id="005" name="kversion">
    <exp>核心版本</exp>
  </expression>
  <expression id="006" name="dversion">
    <exp>Linux 名稱</exp>
  </expression>
  <expression id="007" name="uptime">
    <exp>運作時間</exp>
  </expression>
  <expression id="008" name="users">
    <exp>目前的使用者</exp>
  </expression>
  <expression id="009" name="loadavg">
    <exp>平均負荷</exp>
  </expression>
  <expression id="010" name="hardware">
    <exp>硬體資料</exp>
  </expression>
  <expression id="011" name="numcpu">
    <exp>處理器</exp>
  </expression>
  <expression id="012" name="cpumodel">
    <exp>型號</exp>
  </expression>
  <expression id="013" name="cpuspeed">
    <exp>CPU 速度</exp>
  </expression>
  <expression id="014" name="busspeed">
    <exp>BUS 速度</exp>
  </expression>
  <expression id="015" name="cache">
    <exp>快取大小</exp>
  </expression>
  <expression id="016" name="bogomips">
    <exp>系統 Bogomips</exp>
  </expression>
  <expression id="017" name="pci">
    <exp>PCI 設備</exp>
  </expression>
  <expression id="018" name="ide">
    <exp>IDE 設備</exp>
  </expression>
  <expression id="019" name="scsi">
    <exp>SCSI 設備</exp>
  </expression>
  <expression id="020" name="usb">
    <exp>USB 設備</exp>
  </expression>
  <expression id="021" name="netusage">
    <exp>網路使用率</exp>
  </expression>
  <expression id="022" name="device">
    <exp>設備</exp>
  </expression>
  <expression id="023" name="received">
    <exp>收到</exp>
  </expression>
  <expression id="024" name="sent">
    <exp>送出</exp>
  </expression>
  <expression id="025" name="errors">
    <exp>錯誤/訊號遺失</exp>
  </expression>
  <expression id="026" name="connections">
    <exp>連結網路</exp>
  </expression>
  <expression id="027" name="memusage">
    <exp>記憶使用率</exp>
  </expression>
  <expression id="028" name="phymem">
    <exp>實體記憶</exp>
  </expression>
  <expression id="029" name="swap">
    <exp>硬碟備存 (Disk Swap)</exp>
  </expression>
  <expression id="030" name="fs">
    <exp>掛載檔案系統</exp>
  </expression>
  <expression id="031" name="mount">
    <exp>掛載位置</exp>
  </expression>
  <expression id="032" name="partition">
    <exp>硬碟分割</exp>
  </expression>
  <expression id="033" name="percent">
    <exp>使用率</exp>
  </expression>
  <expression id="034" name="type">
    <exp>類型</exp>
  </expression>
  <expression id="035" name="free">
    <exp>可用</exp>
  </expression>
  <expression id="036" name="used">
    <exp>已用</exp>
  </expression>
  <expression id="037" name="size">
    <exp>大小</exp>
  </expression>
  <expression id="038" name="totals">
    <exp>總共</exp>
  </expression>
  <expression id="039" name="kb">
    <exp>kB</exp>
  </expression>
  <expression id="040" name="mb">
    <exp>MB</exp>
  </expression>
  <expression id="041" name="gb">
    <exp>GB</exp>
  </expression>
  <expression id="042" name="none">
    <exp>沒有</exp>
  </expression>
  <expression id="043" name="capacity">
    <exp>限制</exp>
  </expression>
  <expression id="044" name="template">
    <exp>佈景</exp>
  </expression>
  <expression id="045" name="language">
    <exp>語言</exp>
  </expression>
  <expression id="046" name="submit">
    <exp>送出</exp>
  </expression>
  <expression id="047" name="created">
    <exp>建立於</exp>
  </expression>
  <expression id="048" name="days">
    <exp>天</exp>
  </expression>
  <expression id="049" name="hours">
    <exp>小時</exp>
  </expression>
  <expression id="050" name="minutes">
    <exp>分鐘</exp>
  </expression>
  <expression id="051" name="temperature">
    <exp>溫度</exp>
  </expression>
  <expression id="052" name="voltage">
    <exp>電壓</exp>
  </expression>
  <expression id="053" name="fans">
    <exp>風扇</exp>
  </expression>
  <expression id="054" name="s_value">
    <exp>數值</exp>
  </expression>
  <expression id="055" name="s_min">
    <exp>最小</exp>
  </expression>
  <expression id="056" name="s_max">
    <exp>最大</exp>
  </expression>
  <expression id="057" name="hysteresis">
    <exp>Hysteresis</exp>
  </expression>
  <expression id="058" name="s_limit">
    <exp>限制</exp>
  </expression>
  <expression id="059" name="s_label">
    <exp>標籤</exp>
  </expression>
  <expression id="060" name="degreec">
    <exp>C</exp>
  </expression>
  <expression id="061" name="degreef">
    <exp>F</exp>
  </expression>
  <expression id="062" name="voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="063" name="rpm_mark">
    <exp>RPM</exp>
  </expression>
  <expression id="064" name="app">
    <exp>核心跟軟體</exp>
  </expression>
  <expression id="065" name="buffers">
    <exp>緩衝</exp>
  </expression>
  <expression id="066" name="cached">
    <exp>快取</exp>
  </expression>
  <expression id="067" name="jumpto">
    <exp>跳到</exp>
  </expression>
  <expression id="068" name="ups_title">
    <exp>電源資料</exp>
  </expression>
  <expression id="069" name="ups_name">
    <exp>名稱</exp>
  </expression>
  <expression id="070" name="ups_model">
    <exp>型號</exp>
  </expression>
  <expression id="071" name="ups_mode">
    <exp>模式</exp>
  </expression>
  <expression id="072" name="ups_start_time">
    <exp>已啟動</exp>
  </expression>
  <expression id="073" name="ups_status">
    <exp>狀態</exp>
  </expression>
  <expression id="074" name="ups_outages_count">
    <exp>中斷</exp>
  </expression>
  <expression id="075" name="ups_last_outage">
    <exp>上次中斷原因</exp>
  </expression>
  <expression id="076" name="ups_last_outage_finish">
    <exp>上次中斷時間</exp>
  </expression>
  <expression id="077" name="ups_line_voltage">
    <exp>線路電壓</exp>
  </expression>
  <expression id="078" name="ups_load_percent">
    <exp>負荷百分比</exp>
  </expression>
  <expression id="079" name="ups_battery_voltage">
    <exp>電池電壓</exp>
  </expression>
  <expression id="080" name="ups_battery_charge_percent">
    <exp>電池總額</exp>
  </expression>
  <expression id="081" name="ups_time_left_minutes">
    <exp>電磁餘額時間</exp>
  </expression>
  <expression id="082" name="ups_voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="083" name="ups_minutes_mark">
    <exp>分</exp>
  </expression>
  <expression id="084" name="ups_temperature">
    <exp>溫度</exp>
  </expression>
  <expression id="085" name="tb">
    <exp>TB</exp>
  </expression>
  <expression id="086" name="tib">
    <exp>TiB</exp>
  </expression>
  <expression id="087" name="gib">
    <exp>GiB</exp>
  </expression>
  <expression id="088" name="mib">
    <exp>MiB</exp>
  </expression>
  <expression id="089" name="kib">
    <exp>KiB</exp>
  </expression>
  <expression id="090" name="pib">
    <exp>PiB</exp>
  </expression>
  <expression id="091" name="pb">
    <exp>PB</exp>
  </expression>
  <expression id="092" name="mhz">
    <exp>MHz</exp>
  </expression>
  <expression id="093" name="ghz">
    <exp>GHz</exp>
  </expression>
  <expression id="094" name="virtualization">
    <exp>虛擬化</exp>
  </expression>
  <expression id="095" name="lastboot">
    <exp>Last boot</exp>
  </expression>
  <expression id="096" name="bytes">
    <exp>B</exp>
  </expression>
  <expression id="097" name="syslang">
    <exp>System Language</exp>
  </expression>
  <expression id="098" name="codepage">
    <exp>Code Page</exp>
  </expression>
  <expression id="099" name="details">
    <exp>Details</exp>
  </expression>
  <expression id="100" name="cpuspeedMax">
    <exp>CPU Speed Max</exp>
  </expression>
  <expression id="101" name="cpuspeedMin">
    <exp>CPU Speed Min</exp>
  </expression>
  <expression id="102" name="power">
    <exp>Power</exp>
  </expression>
  <expression id="103" name="power_mark">
    <exp>W</exp>
  </expression>
  <expression id="104" name="ups_battery_date">
    <exp>Battery date</exp>
  </expression>
  <expression id="105" name="current">
    <exp>Current</exp>
  </expression>
  <expression id="106" name="current_mark">
    <exp>A</exp>
  </expression>
  <expression id="107" name="machine">
    <exp>Machine</exp>
  </expression>
  <expression id="108" name="ups_line_frequency">
    <exp>Line frequency</exp>
  </expression>
  <expression id="109" name="Hz">
    <exp>Hz</exp>
  </expression>
  <expression id="110" name="Processes">
    <exp>Processes</exp>
  </expression>
  <expression id="111" name="ProcessesRunning">
    <exp>running</exp>
  </expression>
  <expression id="112" name="ProcessesSleeping">
    <exp>sleeping</exp>
  </expression>
  <expression id="113" name="ProcessesStopped">
    <exp>stopped</exp>
  </expression>
  <expression id="114" name="ProcessesZombie">
    <exp>zombie</exp>
  </expression>
  <expression id="115" name="ProcessesWaiting">
    <exp>waiting</exp>
  </expression>
  <expression id="116" name="ProcessesOther">
    <exp>other</exp>
  </expression>
  <expression id="117" name="tb">
    <exp>TB 設備</exp>
  </expression>
  <expression id="118" name="i2c">
    <exp>I2C 設備</exp>
  </expression>
  <expression id="119" name="no_processors">
    <exp>Number of processors</exp>
  </expression>
  <expression id="120" name="no_devices">
    <exp>Number of devices</exp>
  </expression>
</tns:translation>
