=== sentora/sentora-core/etc/apps/phpsysinfo/language/translation.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!-- $Id: translation.xsd 150 2009-03-20 20:19:23Z bigmichi1 $ -->
<schema targetNamespace="http://phpsysinfo.sourceforge.net/translation"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation" xmlns="http://www.w3.org/2001/XMLSchema">
  <complexType name="translationType">
    <sequence>
      <element name="expression" type="tns:expressionType" maxOccurs="unbounded"
        minOccurs="93">
      </element>
    </sequence>
    <attribute name="charset" type="string" use="required"></attribute>
    <attribute name="language" type="string" use="required"></attribute>
  </complexType>
  <complexType name="expressionType">
    <sequence>
      <element name="exp" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="id" use="required">
      <simpleType>
        <restriction base="string">
          <length value="3"></length>
          <pattern value="\d\d\d"></pattern>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="name" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+"></pattern>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>
  <element name="translation" type="tns:translationType"></element>
</schema>

=== sentora/sentora-core/etc/apps/phpsysinfo/language/cz.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: cz.xml 699 2012-09-15 11:57:13Z namiltd $ -->
<!--
phpSysInfo language file Language: Czech Created by: Peter 'Pessoft' Kolínek
-->
<tns:translation language="czech" charset="utf-8"
 xmlns:tns="http://phpsysinfo.sourceforge.net/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation translation.xsd">
  <expression id="001" name="title">
    <exp>Informace o systému</exp>
  </expression>
  <expression id="002" name="vitals">
    <exp>Základní informace</exp>
  </expression>
  <expression id="003" name="hostname">
    <exp>Kanonické jméno hostitele</exp>
  </expression>
  <expression id="004" name="ip">
    <exp>Poslouchající IP</exp>
  </expression>
  <expression id="005" name="kversion">
    <exp>Verze jádra</exp>
  </expression>
  <expression id="006" name="dversion">
    <exp>Název distribuce</exp>
  </expression>
  <expression id="007" name="uptime">
    <exp>Čas od spuštění</exp>
  </expression>
  <expression id="008" name="users">
    <exp>Přihlášení uživatelé</exp>
  </expression>
  <expression id="009" name="loadavg">
    <exp>Průměrné zatížení</exp>
  </expression>
  <expression id="010" name="hardware">
    <exp>Informace o hardware</exp>
  </expression>
  <expression id="011" name="numcpu">
    <exp>Procesory</exp>
  </expression>
  <expression id="012" name="cpumodel">
    <exp>Model</exp>
  </expression>
  <expression id="013" name="cpuspeed">
    <exp>Rychlost procesoru</exp>
  </expression>
  <expression id="014" name="busspeed">
    <exp>Rychlost sběrnice</exp>
  </expression>
  <expression id="015" name="cache">
    <exp>Velikost cache</exp>
  </expression>
  <expression id="016" name="bogomips">
    <exp>Bogomipsy systému</exp>
  </expression>
  <expression id="017" name="pci">
    <exp>PCI zařízení</exp>
  </expression>
  <expression id="018" name="ide">
    <exp>IDE zařízení</exp>
  </expression>
  <expression id="019" name="scsi">
    <exp>SCSI zařízení</exp>
  </expression>
  <expression id="020" name="usb">
    <exp>USB zařízení</exp>
  </expression>
  <expression id="021" name="netusage">
    <exp>Využití sítě</exp>
  </expression>
  <expression id="022" name="device">
    <exp>Zařízení</exp>
  </expression>
  <expression id="023" name="received">
    <exp>Přijaté</exp>
  </expression>
  <expression id="024" name="sent">
    <exp>Odeslané</exp>
  </expression>
  <expression id="025" name="errors">
    <exp>Chyby/Zahozené</exp>
  </expression>
  <expression id="026" name="connections">
    <exp>Navázaná síťová spojení</exp>
  </expression>
  <expression id="027" name="memusage">
    <exp>Využití paměti</exp>
  </expression>
  <expression id="028" name="phymem">
    <exp>Fyzická paměť</exp>
  </expression>
  <expression id="029" name="swap">
    <exp>Odkládací prostor na disku (Swap)</exp>
  </expression>
  <expression id="030" name="fs">
    <exp>Připojené souborové systémy</exp>
  </expression>
  <expression id="031" name="mount">
    <exp>Přípojný bod</exp>
  </expression>
  <expression id="032" name="partition">
    <exp>Oddíl</exp>
  </expression>
  <expression id="033" name="percent">
    <exp>Využití</exp>
  </expression>
  <expression id="034" name="type">
    <exp>Typ</exp>
  </expression>
  <expression id="035" name="free">
    <exp>Volné</exp>
  </expression>
  <expression id="036" name="used">
    <exp>Použité</exp>
  </expression>
  <expression id="037" name="size">
    <exp>Velikost</exp>
  </expression>
  <expression id="038" name="totals">
    <exp>Celkem</exp>
  </expression>
  <expression id="039" name="kb">
    <exp>KB</exp>
  </expression>
  <expression id="040" name="mb">
    <exp>MB</exp>
  </expression>
  <expression id="041" name="gb">
    <exp>GB</exp>
  </expression>
  <expression id="042" name="none">
    <exp>nic</exp>
  </expression>
  <expression id="043" name="capacity">
    <exp>Kapacita</exp>
  </expression>
  <expression id="044" name="template">
    <exp>Téma vzhledu</exp>
  </expression>
  <expression id="045" name="language">
    <exp>Jazyk</exp>
  </expression>
  <expression id="046" name="submit">
    <exp>Odeslat</exp>
  </expression>
  <expression id="047" name="created">
    <exp>Vytvořeno s</exp>
  </expression>
  <expression id="048" name="days">
    <exp>dní</exp>
  </expression>
  <expression id="049" name="hours">
    <exp>hodin</exp>
  </expression>
  <expression id="050" name="minutes">
    <exp>minut</exp>
  </expression>
  <expression id="051" name="temperature">
    <exp>Teplota</exp>
  </expression>
  <expression id="052" name="voltage">
    <exp>Napětí</exp>
  </expression>
  <expression id="053" name="fans">
    <exp>Ventilátory</exp>
  </expression>
  <expression id="054" name="s_value">
    <exp>Hodnota</exp>
  </expression>
  <expression id="055" name="s_min">
    <exp>Min</exp>
  </expression>
  <expression id="056" name="s_max">
    <exp>Max</exp>
  </expression>
  <expression id="057" name="hysteresis">
    <exp>Hystereze</exp>
  </expression>
  <expression id="058" name="s_limit">
    <exp>Limit</exp>
  </expression>
  <expression id="059" name="s_label">
    <exp>Název</exp>
  </expression>
  <expression id="060" name="degreec">
    <exp>C</exp>
  </expression>
  <expression id="061" name="degreef">
    <exp>F</exp>
  </expression>
  <expression id="062" name="voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="063" name="rpm_mark">
    <exp>RPM</exp>
  </expression>
  <expression id="064" name="app">
    <exp>Jádro + aplikace</exp>
  </expression>
  <expression id="065" name="buffers">
    <exp>Zásobníky</exp>
  </expression>
  <expression id="066" name="cached">
    <exp>Mezipaměť</exp>
  </expression>
  <expression id="067" name="jumpto">
    <exp>Skoč na</exp>
  </expression>
  <expression id="068" name="ups_title">
    <exp>Záložní zdroj</exp>
  </expression>
  <expression id="069" name="ups_name">
    <exp>Název</exp>
  </expression>
  <expression id="070" name="ups_model">
    <exp>Model</exp>
  </expression>
  <expression id="071" name="ups_mode">
    <exp>Režim</exp>
  </expression>
  <expression id="072" name="ups_start_time">
    <exp>Čas od spuštění</exp>
  </expression>
  <expression id="073" name="ups_status">
    <exp>Stav</exp>
  </expression>
  <expression id="074" name="ups_outages_count">
    <exp>Výpadky</exp>
  </expression>
  <expression id="075" name="ups_last_outage">
    <exp>Důvod posledního výpadku</exp>
  </expression>
  <expression id="076" name="ups_last_outage_finish">
    <exp>Čas posledního výpadku</exp>
  </expression>
  <expression id="077" name="ups_line_voltage">
    <exp>Vstupní napětí</exp>
  </expression>
  <expression id="078" name="ups_load_percent">
    <exp>Aktuální zátížení</exp>
  </expression>
  <expression id="079" name="ups_battery_voltage">
    <exp>Napětí na baterii</exp>
  </expression>
  <expression id="080" name="ups_battery_charge_percent">
    <exp>Stav nabití</exp>
  </expression>
  <expression id="081" name="ups_time_left_minutes">
    <exp>Zbývající záložní čas</exp>
  </expression>
  <expression id="082" name="ups_voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="083" name="ups_minutes_mark">
    <exp>minuty</exp>
  </expression>
  <expression id="084" name="ups_temperature">
    <exp>Teplota</exp>
  </expression>
  <expression id="085" name="tb">
    <exp>TB</exp>
  </expression>
  <expression id="086" name="tib">
    <exp>TiB</exp>
  </expression>
  <expression id="087" name="gib">
    <exp>GiB</exp>
  </expression>
  <expression id="088" name="mib">
    <exp>MiB</exp>
  </expression>
  <expression id="089" name="kib">
    <exp>KiB</exp>
  </expression>
  <expression id="090" name="pib">
    <exp>PiB</exp>
  </expression>
  <expression id="091" name="pb">
    <exp>PB</exp>
  </expression>
  <expression id="092" name="mhz">
    <exp>MHz</exp>
  </expression>
  <expression id="093" name="ghz">
    <exp>GHz</exp>
  </expression>
  <expression id="094" name="virtualization">
    <exp>Virtualizace</exp>
  </expression>
  <expression id="095" name="lastboot">
    <exp>Poslední spuštění</exp>
  </expression>
  <expression id="096" name="bytes">
    <exp>B</exp>
  </expression>
  <expression id="097" name="syslang">
    <exp>System Language</exp>
  </expression>
  <expression id="098" name="codepage">
    <exp>Code Page</exp>
  </expression>
  <expression id="099" name="details">
    <exp>Details</exp>
  </expression>
  <expression id="100" name="cpuspeedMax">
    <exp>CPU Speed Max</exp>
  </expression>
  <expression id="101" name="cpuspeedMin">
    <exp>CPU Speed Min</exp>
  </expression>
  <expression id="102" name="power">
    <exp>Power</exp>
  </expression>
  <expression id="103" name="power_mark">
    <exp>W</exp>
  </expression>
  <expression id="104" name="ups_battery_date">
    <exp>Battery date</exp>
  </expression>
  <expression id="105" name="current">
    <exp>Current</exp>
  </expression>
  <expression id="106" name="current_mark">
    <exp>A</exp>
  </expression>
  <expression id="107" name="machine">
    <exp>Machine</exp>
  </expression>
  <expression id="108" name="ups_line_frequency">
    <exp>Line frequency</exp>
  </expression>
  <expression id="109" name="Hz">
    <exp>Hz</exp>
  </expression>
  <expression id="110" name="Processes">
    <exp>Processes</exp>
  </expression>
  <expression id="111" name="ProcessesRunning">
    <exp>running</exp>
  </expression>
  <expression id="112" name="ProcessesSleeping">
    <exp>sleeping</exp>
  </expression>
  <expression id="113" name="ProcessesStopped">
    <exp>stopped</exp>
  </expression>
  <expression id="114" name="ProcessesZombie">
    <exp>zombie</exp>
  </expression>
  <expression id="115" name="ProcessesWaiting">
    <exp>waiting</exp>
  </expression>
  <expression id="116" name="ProcessesOther">
    <exp>other</exp>
  </expression>
</tns:translation>

=== sentora/sentora-core/etc/apps/phpsysinfo/language/pt-br.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: pt-br.xml 699 2012-09-15 11:57:13Z namiltd $ -->
<!--
phpSysInfo language file Language: Brazilian Portuguese Created by:
Giancarlo Gil Ottaviani Raduan graduan at gmail.com
-->
<tns:translation language="french" charset="utf-8"
 xmlns:tns="http://phpsysinfo.sourceforge.net/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation translation.xsd">
  <expression id="001" name="title">
    <exp>Informacao do Sistema</exp>
  </expression>
  <expression id="002" name="vitals">
    <exp>Sistema Vital</exp>
  </expression>
  <expression id="003" name="hostname">
    <exp>Nome do Host Canonico</exp>
  </expression>
  <expression id="004" name="ip">
    <exp>Ouvindo o IP</exp>
  </expression>
  <expression id="005" name="kversion">
    <exp>Versao do Kernel</exp>
  </expression>
  <expression id="006" name="dversion">
    <exp>Distribuicao</exp>
  </expression>
  <expression id="007" name="uptime">
    <exp>Ativo</exp>
  </expression>
  <expression id="008" name="users">
    <exp>Usuarios Ativos</exp>
  </expression>
  <expression id="009" name="loadavg">
    <exp>Carga Media</exp>
  </expression>
  <expression id="010" name="hardware">
    <exp>Informacao do Hardware</exp>
  </expression>
  <expression id="011" name="numcpu">
    <exp>Processadores</exp>
  </expression>
  <expression id="012" name="cpumodel">
    <exp>Modelo</exp>
  </expression>
  <expression id="013" name="cpuspeed">
    <exp>CPU velocidade</exp>
  </expression>
  <expression id="014" name="busspeed">
    <exp>BUS velocidade</exp>
  </expression>
  <expression id="015" name="cache">
    <exp>Tamanho do Cache</exp>
  </expression>
  <expression id="016" name="bogomips">
    <exp>Bogomips do Sistema</exp>
  </expression>
  <expression id="017" name="pci">
    <exp>Perifericos PCI</exp>
  </expression>
  <expression id="018" name="ide">
    <exp>Perifericos IDE</exp>
  </expression>
  <expression id="019" name="scsi">
    <exp>Perifericos SCSI</exp>
  </expression>
  <expression id="020" name="usb">
    <exp>Perifericos USB</exp>
  </expression>
  <expression id="021" name="netusage">
    <exp>Uso da Rede</exp>
  </expression>
  <expression id="022" name="device">
    <exp>Dispositivo</exp>
  </expression>
  <expression id="023" name="received">
    <exp>Recebido</exp>
  </expression>
  <expression id="024" name="sent">
    <exp>Enviado</exp>
  </expression>
  <expression id="025" name="errors">
    <exp>Erro/Perdido</exp>
  </expression>
  <expression id="026" name="connections">
    <exp>Conexoes de Rede Estabilizadas</exp>
  </expression>
  <expression id="027" name="memusage">
    <exp>Uso da Memoria</exp>
  </expression>
  <expression id="028" name="phymem">
    <exp>Memoria Fisica</exp>
  </expression>
  <expression id="029" name="swap">
    <exp>Swap do Disco</exp>
  </expression>
  <expression id="030" name="fs">
    <exp>Sistemas de Arquivos Montados</exp>
  </expression>
  <expression id="031" name="mount">
    <exp>Ponto Montado</exp>
  </expression>
  <expression id="032" name="partition">
    <exp>Particao</exp>
  </expression>
  <expression id="033" name="percent">
    <exp>Percentual</exp>
  </expression>
  <expression id="034" name="type">
    <exp>Tipo</exp>
  </expression>
  <expression id="035" name="free">
    <exp>Livre</exp>
  </expression>
  <expression id="036" name="used">
    <exp>Usado</exp>
  </expression>
  <expression id="037" name="size">
    <exp>Tamanho</exp>
  </expression>
  <expression id="038" name="totals">
    <exp>Totais</exp>
  </expression>
  <expression id="039" name="kb">
    <exp>KB</exp>
  </expression>
  <expression id="040" name="mb">
    <exp>MB</exp>
  </expression>
  <expression id="041" name="gb">
    <exp>GB</exp>
  </expression>
  <expression id="042" name="none">
    <exp>nenhum</exp>
  </expression>
  <expression id="043" name="capacity">
    <exp>Capacidade</exp>
  </expression>
  <expression id="044" name="template">
    <exp>Estilo</exp>
  </expression>
  <expression id="045" name="language">
    <exp>Idioma</exp>
  </expression>
  <expression id="046" name="submit">
    <exp>Submeter</exp>
  </expression>
  <expression id="047" name="created">
    <exp>Criado por</exp>
  </expression>
  <expression id="048" name="days">
    <exp>dias</exp>
  </expression>
  <expression id="049" name="hours">
    <exp>horas</exp>
  </expression>
  <expression id="050" name="minutes">
    <exp>minutos</exp>
  </expression>
  <expression id="051" name="temperature">
    <exp>Temperatura</exp>
  </expression>
  <expression id="052" name="voltage">
    <exp>Voltagem</exp>
  </expression>
  <expression id="053" name="fans">
    <exp>Ventiladores</exp>
  </expression>
  <expression id="054" name="s_value">
    <exp>Valor</exp>
  </expression>
  <expression id="055" name="s_min">
    <exp>Min</exp>
  </expression>
  <expression id="056" name="s_max">
    <exp>Max</exp>
  </expression>
  <expression id="057" name="hysteresis">
    <exp>Hysteresis</exp>
  </expression>
  <expression id="058" name="s_limit">
    <exp>Limite</exp>
  </expression>
  <expression id="059" name="s_label">
    <exp>Rotulos</exp>
  </expression>
  <expression id="060" name="degreec">
    <exp>C</exp>
  </expression>
  <expression id="061" name="degreef">
    <exp>F</exp>
  </expression>
  <expression id="062" name="voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="063" name="rpm_mark">
    <exp>RPM</exp>
  </expression>
  <expression id="064" name="app">
    <exp>Kernel + aplicacoes</exp>
  </expression>
  <expression id="065" name="buffers">
    <exp>Buffers</exp>
  </expression>
  <expression id="066" name="cached">
    <exp>Cached</exp>
  </expression>
  <expression id="067" name="jumpto">
    <exp>Ir para</exp>
  </expression>
  <expression id="068" name="ups_title">
    <exp>Informacao do UPS</exp>
  </expression>
  <expression id="069" name="ups_name">
    <exp>Nome</exp>
  </expression>
  <expression id="070" name="ups_model">
    <exp>Modelo</exp>
  </expression>
  <expression id="071" name="ups_mode">
    <exp>Modo</exp>
  </expression>
  <expression id="072" name="ups_start_time">
    <exp>Iniciado</exp>
  </expression>
  <expression id="073" name="ups_status">
    <exp>Estatus</exp>
  </expression>
  <expression id="074" name="ups_outages_count">
    <exp>Queda</exp>
  </expression>
  <expression id="075" name="ups_last_outage">
    <exp>Causa da Ultima Queda</exp>
  </expression>
  <expression id="076" name="ups_last_outage_finish">
    <exp>Ultimo registro de Queda</exp>
  </expression>
  <expression id="077" name="ups_line_voltage">
    <exp>Voltagem de linha</exp>
  </expression>
  <expression id="078" name="ups_load_percent">
    <exp>Carga porcentual</exp>
  </expression>
  <expression id="079" name="ups_battery_voltage">
    <exp>Voltagem da bateria</exp>
  </expression>
  <expression id="080" name="ups_battery_charge_percent">
    <exp>Carga da bateria</exp>
  </expression>
  <expression id="081" name="ups_time_left_minutes">
    <exp>Tempo restante das baterias</exp>
  </expression>
  <expression id="082" name="ups_voltage_mark">
    <exp>V</exp>
  </expression>
  <expression id="083" name="ups_minutes_mark">
    <exp>minutos</exp>
  </expression>
  <expression id="084" name="ups_temperature">
    <exp>Temperatura</exp>
  </expression>
  <expression id="085" name="tb">
    <exp>TB</exp>
  </expression>
  <expression id="086" name="tib">
    <exp>TiB</exp>
  </expression>
  <expression id="087" name="gib">
    <exp>GiB</exp>
  </expression>
  <expression id="088" name="mib">
    <exp>MiB</exp>
  </expression>
  <expression id="089" name="kib">
    <exp>KiB</exp>
  </expression>
  <expression id="090" name="pib">
    <exp>PiB</exp>
  </expression>
  <expression id="091" name="pb">
    <exp>PB</exp>
  </expression>
  <expression id="092" name="mhz">
    <exp>MHz</exp>
  </expression>
  <expression id="093" name="ghz">
    <exp>GHz</exp>
  </expression>
  <expression id="094" name="virtualization">
    <exp>Virtualization</exp>
  </expression>
  <expression id="095" name="lastboot">
    <exp>Last boot</exp>
  </expression>
  <expression id="096" name="bytes">
    <exp>B</exp>
  </expression>
  <expression id="097" name="syslang">
    <exp>System Language</exp>
  </expression>
  <expression id="098" name="codepage">
    <exp>Code Page</exp>
  </expression>
  <expression id="099" name="details">
    <exp>Details</exp>
  </expression>
  <expression id="100" name="cpuspeedMax">
    <exp>CPU Speed Max</exp>
  </expression>
  <expression id="101" name="cpuspeedMin">
    <exp>CPU Speed Min</exp>
  </expression>
  <expression id="102" name="power">
    <exp>Power</exp>
  </expression>
  <expression id="103" name="power_mark">
    <exp>W</exp>
  </expression>
  <expression id="104" name="ups_battery_date">
    <exp>Battery date</exp>
  </expression>
  <expression id="105" name="current">
    <exp>Current</exp>
  </expression>
  <expression id="106" name="current_mark">
    <exp>A</exp>
  </expression>
  <expression id="107" name="machine">
    <exp>Machine</exp>
  </expression>
  <expression id="108" name="ups_line_frequency">
    <exp>Line frequency</exp>
  </expression>
  <expression id="109" name="Hz">
    <exp>Hz</exp>
  </expression>
</tns:translation>
