=== sentora/sentora-core/etc/apps/phpsysinfo/language/translation-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!-- $Id: translation-plugin.xsd 36 2008-12-08 09:45:45Z BigMichi1 $ -->
<schema targetNamespace="http://phpsysinfo.sourceforge.net/translation-plugin"
  xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin">
  <complexType name="translationPluginType">
    <sequence>
      <element name="expression" type="tns:expressionPluginType"
        maxOccurs="unbounded" minOccurs="1">
      </element>
    </sequence>
    <attribute name="charset" type="string" use="required"></attribute>
    <attribute name="language" type="string" use="required"></attribute>
  </complexType>
  <complexType name="expressionPluginType">
    <sequence>
      <element name="exp" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="id" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+\d\d\d"></pattern>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="name" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+"></pattern>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>
  <element name="translationPlugin" type="tns:translationPluginType"></element>
</schema>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/dmraid/lang/fr.xml
<?xml version="1.0" encoding="utf-8"?>
  <!--
    phpSysInfo language file Language: French Created by: phpsysinfo
  -->
<tns:translationPlugin language="french" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_dmraid_001" name="dmraid_title">
    <exp>Statut RAID</exp>
  </expression>
  <expression id="plugin_dmraid_002" name="dmraid_devices">
    <exp>Périphériques RAID</exp>
  </expression>
  <expression id="plugin_dmraid_003" name="dmraid_infos">
    <exp>Informations additionnelles</exp>
  </expression>
  <expression id="plugin_dmraid_004" name="dmraid_name">
    <exp>Nom</exp>
  </expression>
  <expression id="plugin_dmraid_005" name="dmraid_status">
    <exp>Status</exp>
  </expression>
  <expression id="plugin_dmraid_006" name="dmraid_type">
    <exp>Type de RAID</exp>
  </expression>
  <expression id="plugin_dmraid_007" name="dmraid_size">
    <exp>Taille</exp>
  </expression>
  <expression id="plugin_dmraid_008" name="dmraid_stride">
    <exp>Granularité</exp>
  </expression>
  <expression id="plugin_dmraid_009" name="dmraid_subsets">
    <exp>Sous-ensembles</exp>
  </expression>
  <expression id="plugin_dmraid_010" name="dmraid_devs">
    <exp>Périphériques</exp>
  </expression>
  <expression id="plugin_dmraid_011" name="dmraid_spares">
    <exp>Rechanges</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ps/lang/fr.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: fr.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: French Created by: Erkan VALENTIN
  -->
<tns:translationPlugin language="french" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ps_001" name="ps_title">
    <exp>Etat des processus</exp>
  </expression>
  <expression id="plugin_ps_002" name="ps_command">
    <exp>Commande</exp>
  </expression>
  <expression id="plugin_ps_003" name="ps_pid">
    <exp>ID processus</exp>
  </expression>
  <expression id="plugin_ps_004" name="ps_ppid">
    <exp>ID processus père</exp>
  </expression>
  <expression id="plugin_ps_005" name="ps_mem">
    <exp>Utilisation mémoire</exp>
  </expression>
  <expression id="plugin_ps_006" name="ps_cpu">
    <exp>CPU Usage</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/snmppinfo/lang/de.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: de.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: German Created by: Matthias Freund (MAFLO321)
  -->
<tns:translationPlugin language="german" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_snmppinfo_001" name="snmppinfo_title">
    <exp>Drucker Information</exp>
  </expression>
  <expression id="plugin_snmppinfo_002" name="snmppinfo_date">
    <exp>Letzte Aktualisierung</exp>
  </expression>
  <expression id="plugin_snmppinfo_003" name="snmppinfo_printer">
    <exp>Drucker</exp>
  </expression>
  <expression id="plugin_snmppinfo_004" name="snmppinfo_percent">
    <exp>Prozent</exp>
  </expression>
  <expression id="plugin_snmppinfo_005" name="snmppinfo_units">
    <exp>Units</exp>
  </expression>
  <expression id="plugin_snmppinfo_006" name="snmppinfo_enough">
    <exp>genug</exp>
  </expression>
  <expression id="plugin_snmppinfo_007" name="snmppinfo_unknown">
    <exp>unbekannt</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/uprecords/lang/ru.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ru.xml 661 2015-01-05 11:26:39Z $ -->
  <!--
    phpSysInfo language file Language: Russian Created by: Denis Sevostyanov (den007)
  -->
<tns:translationPlugin language="english" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_uprecords_001" name="uprecords_title">
    <exp>Состояное системы</exp>
  </expression>
  <expression id="plugin_uprecords_002" name="uprecords_date">
    <exp>Последние обновление</exp>
  </expression>
  <expression id="plugin_uprecords_101" name="uprecords_hash">
    <exp>#</exp>
  </expression>
  <expression id="plugin_uprecords_102" name="uprecords_uptime">
    <exp>Аптайм</exp>
  </expression>
  <expression id="plugin_uprecords_103" name="uprecords_system">
    <exp>Система</exp>
  </expression>
  <expression id="plugin_uprecords_104" name="uprecords_bootup">
    <exp>Загружено</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/bat/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Romană Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_bat_001" name="bat_title">
    <exp>Stare Baterie</exp>
  </expression>
  <expression id="plugin_bat_002" name="bat_date">
    <exp>Ultimul refresh</exp>
  </expression>
  <expression id="plugin_bat_003" name="bat_design_capacity">
    <exp>Capacitate Design</exp>
  </expression>
  <expression id="plugin_bat_004" name="bat_remaining_capacity">
    <exp>Capacitate rămasă</exp>
  </expression>
  <expression id="plugin_bat_005" name="bat_design_voltage">
    <exp>Voltaj design</exp>
  </expression>
  <expression id="plugin_bat_006" name="bat_present_voltage">
    <exp>Voltaj prezent</exp>
  </expression>
  <expression id="plugin_bat_007" name="bat_item">
    <exp>Elemente</exp>
  </expression>
  <expression id="plugin_bat_008" name="bat_value">
    <exp>Valori</exp>
  </expression>
  <expression id="plugin_bat_009" name="bat_charging_state">
    <exp>Stare de Încărcare</exp>
  </expression>
  <expression id="plugin_bat_010" name="bat_battery_type">
    <exp>Tip Baterie</exp>
  </expression>
  <expression id="plugin_bat_011" name="bat_battery_temperature">
    <exp>Temperatura Baterie</exp>
  </expression>
  <expression id="plugin_bat_012" name="bat_battery_condition">
    <exp>Condiții Baterie</exp>
  </expression>
  <expression id="plugin_bat_013" name="bat_cycle_count">
    <exp>Cycle Count</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/quotas/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Romană Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_quotas_001" name="ps_title">
    <exp>Stare Quota</exp>
  </expression>
  <expression id="plugin_quotas_002" name="quotas_date">
    <exp>Ultimul refresh</exp>
  </expression>
  <expression id="plugin_quotas_003" name="quotas_user">
    <exp>Utilizator</exp>
  </expression>
  <expression id="plugin_quotas_004" name="quotas_bused">
    <exp>Bytes Folositi</exp>
  </expression>
  <expression id="plugin_quotas_005" name="quotas_bsoft">
    <exp>Bytes Soft</exp>
  </expression>
  <expression id="plugin_quotas_006" name="quotas_bhard">
    <exp>Bytes Hard</exp>
  </expression>
  <expression id="plugin_quotas_007" name="quotas_bpuse">
    <exp>Bytes Percent Folosiți</exp>
  </expression>
  <expression id="plugin_quotas_008" name="quotas_fused">
    <exp>Fișiere Folosite</exp>
  </expression>
  <expression id="plugin_quotas_009" name="quotas_fsoft">
    <exp>Fișiere Soft</exp>
  </expression>
  <expression id="plugin_quotas_010" name="quotas_fhard">
    <exp>Fișiere Hard</exp>
  </expression>
  <expression id="plugin_quotas_011" name="quotas_fpuse">
    <exp>Fișiere Percent Folosite</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/raid/lang/de.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: de.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: German Created by: Michael Cramer
  -->
<tns:translationPlugin language="german" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_raid_001" name="raid_title">
    <exp>RAID Status</exp>
  </expression>
  <expression id="plugin_raid_002" name="raid_infos">
    <exp>Zusätzliche Informationen</exp>
  </expression>
  <expression id="plugin_raid_003" name="raid_name">
    <exp>Name</exp>
  </expression>
  <expression id="plugin_raid_004" name="raid_status">
    <exp>Status</exp>
  </expression>
  <expression id="plugin_raid_005" name="raid_level">
    <exp>RAID-Level</exp>
  </expression>
  <expression id="plugin_raid_006" name="raid_size">
    <exp>Size</exp>
  </expression>
  <expression id="plugin_raid_007" name="raid_stride">
    <exp>Stride</exp>
  </expression>
  <expression id="plugin_raid_008" name="raid_subsets">
    <exp>Subsets</exp>
  </expression>
  <expression id="plugin_raid_009" name="raid_devs">
    <exp>Devices</exp>
  </expression>
  <expression id="plugin_raid_010" name="raid_spares">
    <exp>Spares</exp>
  </expression>
  <expression id="plugin_raid_011" name="raid_curact">
    <exp>Current Action</exp>
  </expression>
  <expression id="plugin_raid_012" name="raid_finish">
    <exp>Fertig in</exp>
  </expression>
  <expression id="plugin_raid_013" name="raid_chunk">
    <exp>Blockgröße</exp>
  </expression>
  <expression id="plugin_raid_014" name="raid_algo">
    <exp>Algorithmus</exp>
  </expression>
  <expression id="plugin_raid_015" name="raid_superb">
    <exp>Persistenter Superblock</exp>
  </expression>
  <expression id="plugin_raid_016" name="raid_avail">
    <exp>verfügbar</exp>
  </expression>
  <expression id="plugin_raid_017" name="raids_navail">
    <exp>nicht verfügbar</exp>
  </expression>
  <expression id="plugin_raid_018" name="raid_regact">
    <exp>Registrierte/Aktive Platten</exp>
  </expression>
  <expression id="plugin_raid_019" name="raid_controller">
    <exp>Controller</exp>
  </expression>
  <expression id="plugin_raid_020" name="raid_battcond">
    <exp>Akku-Zustand</exp>
  </expression>
  <expression id="plugin_raid_021" name="raid_supported">
    <exp>Unterstützte RAID-Typen</exp>
  </expression>
  <expression id="plugin_raid_022" name="raid_program">
    <exp>Program</exp>
  </expression>
  <expression id="plugin_raid_023" name="raid_readpolicy">
    <exp>Read Policy</exp>
  </expression>
  <expression id="plugin_raid_024" name="raid_writepolicy">
    <exp>Write Policy</exp>
  </expression>
  <expression id="plugin_raid_025" name="raid_cachesize">
    <exp>Cache Size</exp>
  </expression>
  <expression id="plugin_raid_026" name="raid_badblocks">
    <exp>Bad Blocks</exp>
  </expression>
  <expression id="plugin_raid_027" name="raid_diskcache">
    <exp>Disk Cache</exp>
  </expression>
  <expression id="plugin_raid_028" name="raid_stripe">
    <exp>Stripe Size</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ipmiinfo/lang/en.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: en.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: English Created by: Mieczyslaw Nalewaj
  -->
<tns:translationPlugin language="english" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ipmiinfo_001" name="ipmiinfo_title">
    <exp>IPMI Status</exp>
  </expression>
  <expression id="plugin_ipmiinfo_002" name="ipmiinfo_date">
    <exp>Last refresh</exp>
  </expression>
  <expression id="plugin_ipmiinfo_003" name="ipmiinfo_temperatures">
    <exp>Temperatures [Â°C]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_004" name="ipmiinfo_fans">
    <exp>Fans [RPM]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_005" name="ipmiinfo_voltages">
    <exp>Voltages [V]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_006" name="ipmiinfo_misc">
    <exp>Misc [0/1]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_007" name="ipmiinfo_currents">
    <exp>Currents [A]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_008" name="ipmiinfo_powers">
    <exp>Powers [W]</exp>
  </expression>
</tns:translationPlugin>
