=== sentora/sentora-core/etc/apps/phpsysinfo/language/translation-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!-- $Id: translation-plugin.xsd 36 2008-12-08 09:45:45Z BigMichi1 $ -->
<schema targetNamespace="http://phpsysinfo.sourceforge.net/translation-plugin"
  xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin">
  <complexType name="translationPluginType">
    <sequence>
      <element name="expression" type="tns:expressionPluginType"
        maxOccurs="unbounded" minOccurs="1">
      </element>
    </sequence>
    <attribute name="charset" type="string" use="required"></attribute>
    <attribute name="language" type="string" use="required"></attribute>
  </complexType>
  <complexType name="expressionPluginType">
    <sequence>
      <element name="exp" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="id" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+\d\d\d"></pattern>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="name" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+"></pattern>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>
  <element name="translationPlugin" type="tns:translationPluginType"></element>
</schema>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/quotas/lang/en.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: en.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: English Created by: Michael Cramer
  -->
<tns:translationPlugin language="english" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_quotas_001" name="ps_title">
    <exp>Quota Status</exp>
  </expression>
  <expression id="plugin_quotas_002" name="quotas_date">
    <exp>Last Refresh</exp>
  </expression>
  <expression id="plugin_quotas_003" name="quotas_user">
    <exp>User</exp>
  </expression>
  <expression id="plugin_quotas_004" name="quotas_bused">
    <exp>Bytes Used</exp>
  </expression>
  <expression id="plugin_quotas_005" name="quotas_bsoft">
    <exp>Bytes Soft</exp>
  </expression>
  <expression id="plugin_quotas_006" name="quotas_bhard">
    <exp>Bytes Hard</exp>
  </expression>
  <expression id="plugin_quotas_007" name="quotas_bpuse">
    <exp>Bytes Used Percent</exp>
  </expression>
  <expression id="plugin_quotas_008" name="quotas_fused">
    <exp>Files Used</exp>
  </expression>
  <expression id="plugin_quotas_009" name="quotas_fsoft">
    <exp>Files Soft</exp>
  </expression>
  <expression id="plugin_quotas_010" name="quotas_fhard">
    <exp>Files Hard</exp>
  </expression>
  <expression id="plugin_quotas_011" name="quotas_fpuse">
    <exp>Files Used Percent</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/mdstatus/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Romană Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_mdstatus_001" name="mdstatus_title">
    <exp>Stare RAID</exp>
  </expression>
  <expression id="plugin_mdstatus_002" name="mdstatus_support">
    <exp>Tipuri de RAID suportate</exp>
  </expression>
  <expression id="plugin_mdstatus_003" name="mdstatus_devices">
    <exp>Dispozitive RAID</exp>
  </expression>
  <expression id="plugin_mdstatus_004" name="mdstatus_infos">
    <exp>Informații Aditionale</exp>
  </expression>
  <expression id="plugin_mdstatus_005" name="mdstatus_status">
    <exp>Stare</exp>
  </expression>
  <expression id="plugin_mdstatus_006" name="mdstatus_level">
    <exp>Nivele RAID</exp>
  </expression>
  <expression id="plugin_mdstatus_007" name="mdstatus_chunk">
    <exp>Chunk Size</exp>
  </expression>
  <expression id="plugin_mdstatus_008" name="mdstatus_algo">
    <exp>Algoritm</exp>
  </expression>
  <expression id="plugin_mdstatus_009" name="mdstatus_superb">
    <exp>Superblock persistente</exp>
  </expression>
  <expression id="plugin_mdstatus_010" name="mdstatus_avail">
    <exp>disponibil</exp>
  </expression>
  <expression id="plugin_mdstatus_011" name="mdstatus_navail">
    <exp>indisponibil</exp>
  </expression>
  <expression id="plugin_mdstatus_012" name="mdstatus_regact">
    <exp>Înregistrate/Discuri Active</exp>
  </expression>
  <expression id="plugin_mdstatus_013" name="mdstatus_curact">
    <exp>Acțiune curentă</exp>
  </expression>
  <expression id="plugin_mdstatus_014" name="mdstatus_finishin">
    <exp>finisare în</exp>
  </expression>
  <expression id="plugin_mdstatus_015" name="mdstatus_unused">
    <exp>Discuri defolosite</exp>
  </expression>
  <expression id="plugin_mdstatus_016" name="mdstatus_refresh">
    <exp>Ultimul refresh</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/uprecords/lang/pl.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: pl.xml 661 2014-01-08 11:26:39Z aolah76 $ -->
  <!--
    phpSysInfo language file Language: Polish Created by: Created by: Mieczyslaw Nalewaj
  -->
<tns:translationPlugin language="polish" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_uprecords_001" name="uprecords_title">
    <exp>Uprecords</exp>
  </expression>
  <expression id="plugin_uprecords_101" name="uprecords_hash">
    <exp>#</exp>
  </expression>
  <expression id="plugin_uprecords_102" name="uprecords_uptime">
    <exp>Czas pracy</exp>
  </expression>
  <expression id="plugin_uprecords_103" name="uprecords_system">
    <exp>System</exp>
  </expression>
  <expression id="plugin_uprecords_104" name="uprecords_bootup">
    <exp>Wystartowa≈Ç</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/pingtest/lang/pl.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: pl.xml 661 2017-09-01 09:01:17Z namiltd $ -->
<!--
phpSysInfo language file Language: Polish Created by: Mieczyslaw Nalewaj
-->
<tns:translationPlugin language="polish" charset="utf-8"
 xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_pingtest_001" name="pingtest_title">
    <exp>Test Pingu</exp>
  </expression>
  <expression id="plugin_pingtest_002" name="pingtest_address">
    <exp>Adres</exp>
  </expression>
  <expression id="plugin_pingtest_003" name="pingtest_pingtime">
    <exp>Czas Pingu</exp>
  </expression>
  <expression id="plugin_pingtest_004" name="pingtest_lost">
    <exp>zagubiony</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/smart/lang/cz.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: cz.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Czech Created by: Tomáš Růžička
  -->
<tns:translationPlugin language="czech" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_smart_001" name="smart_title">
    <exp>S.M.A.R.T Informace</exp>
  </expression>
  <expression id="plugin_smart_002" name="smart_date">
    <exp>Aktualizováno</exp>
  </expression>
  <expression id="plugin_smart_003" name="smart_name">
    <exp>Název</exp>
  </expression>
  <expression id="plugin_smart_101" name="smart_raw_read_error_rate">
    <exp>Raw Read Error Rate</exp>
  </expression>
  <expression id="plugin_smart_102" name="smart_throughput_performance">
    <exp>Throughput Performance</exp>
  </expression>
  <expression id="plugin_smart_103" name="smart_spin_up_time">
    <exp>Spin Up Time</exp>
  </expression>
  <expression id="plugin_smart_104" name="smart_start_stop_count">
    <exp>Start Stop Count</exp>
  </expression>
  <expression id="plugin_smart_105" name="smart_reallocated_sector_ct">
    <exp>Reallocated Sector Ct</exp>
  </expression>
  <expression id="plugin_smart_107" name="smart_seek_error_rate">
    <exp>Seek Error Rate</exp>
  </expression>
  <expression id="plugin_smart_108" name="smart_seek_time_performance">
    <exp>Seek Time Performance</exp>
  </expression>
  <expression id="plugin_smart_109" name="smart_power_on_hours">
    <exp>Power On Hours</exp>
  </expression>
  <expression id="plugin_smart_110" name="smart_spin_retry_count">
    <exp>Spin Retry Count</exp>
  </expression>
  <expression id="plugin_smart_111" name="smart_calibration_retry_count">
    <exp>Calibration Retry Count</exp>
  </expression>
  <expression id="plugin_smart_112" name="smart_power_cycle_count">
    <exp>Power Cycle Count</exp>
  </expression>
  <expression id="plugin_smart_290" name="smart_airflow_temperature_cel">
    <exp>Airflow Temperature</exp>
  </expression>
  <expression id="plugin_smart_291" name="smart_g_sense_error_rate">
    <exp>G-sense Error Rate</exp>
  </expression>
  <expression id="plugin_smart_292" name="smart_power_off_retry_count">
    <exp>Power-Off Retract Count</exp>
  </expression>
  <expression id="plugin_smart_293" name="smart_load_cycle_count">
    <exp>Load Cycle Count</exp>
  </expression>
  <expression id="plugin_smart_294" name="smart_temperature">
    <exp>Temperature</exp>
  </expression>
  <expression id="plugin_smart_295" name="smart_hardware_ecc_recovered">
    <exp>Hardware ECC Recovered</exp>
  </expression>
  <expression id="plugin_smart_296" name="smart_reallocated_event_count">
    <exp>Reallocated Event Count</exp>
  </expression>
  <expression id="plugin_smart_297" name="smart_current_pending_sector">
    <exp>Current Pending Sector</exp>
  </expression>
  <expression id="plugin_smart_298" name="smart_offline_uncorrectable">
    <exp>Offline Uncorr.</exp>
  </expression>
  <expression id="plugin_smart_299" name="smart_udma_crc_error_count">
    <exp>UDMA CRC Error Count</exp>
  </expression>
  <expression id="plugin_smart_300" name="smart_multi_zone_error_rate">
    <exp>Multi Zone Error Rate</exp>
  </expression>
  <expression id="plugin_smart_301" name="smart_soft_read_error_rate">
    <exp>Soft Read Error Rate</exp>
  </expression>
  <expression id="plugin_smart_302" name="smart_data_address_mark_errs">
    <exp>Data Address Mark Errors</exp>
  </expression>
  <expression id="plugin_smart_323" name="smart_load_retry_count">
    <exp>Load Retry Count</exp>
  </expression>
  <expression id="plugin_smart_325" name="smart_load_cycle_count_alt">
    <exp>Load Cycle Count</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ps/lang/pl.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: pl.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Polish Created by: Mieczyslaw Nalewaj
  -->
<tns:translationPlugin language="polish" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ps_001" name="ps_title">
    <exp>Status Procesów</exp>
  </expression>
  <expression id="plugin_ps_002" name="ps_command">
    <exp>Polecenie</exp>
  </expression>
  <expression id="plugin_ps_003" name="ps_pid">
    <exp>PID</exp>
  </expression>
  <expression id="plugin_ps_004" name="ps_ppid">
    <exp>PID rodzica</exp>
  </expression>
  <expression id="plugin_ps_005" name="ps_mem">
    <exp>Wykorzystanie pamięci</exp>
  </expression>
  <expression id="plugin_ps_006" name="ps_cpu">
    <exp>Wykorzystanie procesora</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ps/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: RomanÄƒ Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ps_001" name="ps_title">
    <exp>Stare proces</exp>
  </expression>
  <expression id="plugin_ps_002" name="ps_date">
    <exp>Ultimul refresh</exp>
  </expression>
  <expression id="plugin_ps_003" name="ps_command">
    <exp>Comanda</exp>
  </expression>
  <expression id="plugin_ps_004" name="ps_pid">
    <exp>ID Proces</exp>
  </expression>
  <expression id="plugin_ps_005" name="ps_ppid">
    <exp>ID Parinte</exp>
  </expression>
  <expression id="plugin_ps_006" name="ps_mem">
    <exp>Utilizare Memorie</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ps/lang/gr.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: gr.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Greek Created by: mojiro
  -->
<tns:translationPlugin language="greek" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ps_001" name="ps_title">
    <exp>Διεργασίες Συστήματος</exp>
  </expression>
  <expression id="plugin_ps_002" name="ps_command">
    <exp>Εντολή</exp>
  </expression>
  <expression id="plugin_ps_003" name="ps_pid">
    <exp>ID Διεργασίας</exp>
  </expression>
  <expression id="plugin_ps_004" name="ps_ppid">
    <exp>ID Κύριας Διεργασίας</exp>
  </expression>
  <expression id="plugin_ps_005" name="ps_mem">
    <exp>Χρήση Μνήμης</exp>
  </expression>
  <expression id="plugin_ps_006" name="ps_cpu">
    <exp>Χρήση Επεξεργαστή</exp>
  </expression>
</tns:translationPlugin>
