=== sentora/sentora-core/etc/apps/phpsysinfo/language/translation-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <!-- $Id: translation-plugin.xsd 36 2008-12-08 09:45:45Z BigMichi1 $ -->
<schema targetNamespace="http://phpsysinfo.sourceforge.net/translation-plugin"
  xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin">
  <complexType name="translationPluginType">
    <sequence>
      <element name="expression" type="tns:expressionPluginType"
        maxOccurs="unbounded" minOccurs="1">
      </element>
    </sequence>
    <attribute name="charset" type="string" use="required"></attribute>
    <attribute name="language" type="string" use="required"></attribute>
  </complexType>
  <complexType name="expressionPluginType">
    <sequence>
      <element name="exp" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="id" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+\d\d\d"></pattern>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="name" use="required">
      <simpleType>
        <restriction base="string">
          <pattern value="[a-z_]+"></pattern>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>
  <element name="translationPlugin" type="tns:translationPluginType"></element>
</schema>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ipmiinfo/lang/pl.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: pl.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Polish Created by: Mieczyslaw Nalewaj
  -->
<tns:translationPlugin language="polish" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ipmiinfo_001" name="ipmiinfo_title">
    <exp>IPMI Status</exp>
  </expression>
  <expression id="plugin_ipmiinfo_002" name="ipmiinfo_date">
    <exp>Ostatnie odświeżenie</exp>
  </expression>
  <expression id="plugin_ipmiinfo_003" name="ipmiinfo_temperatures">
    <exp>Temperatury [°C]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_004" name="ipmiinfo_fans">
    <exp>Wentylatory [RPM]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_005" name="ipmiinfo_voltages">
    <exp>Napięcia [V]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_006" name="ipmiinfo_misc">
    <exp>Różne [0/1]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_007" name="ipmiinfo_currents">
    <exp>Prądy [A]</exp>
  </expression>
  <expression id="plugin_ipmiinfo_008" name="ipmiinfo_powers">
    <exp>Moce [W]</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/updatenotifier/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Romană Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_updatenotifier_001" name="updatenotifier_title">
    <exp>Updates Notifier</exp>
  </expression>
  <expression id="plugin_updatenotifier_002" name="updatenotifier_th">
    <exp>Actualizări Disponibile</exp>
  </expression>
  <expression id="plugin_updatenotifier_003" name="updatenotifier_packages">
    <exp>Pachetele pot fi actualizate.</exp>
  </expression>
  <expression id="plugin_updatenotifier_004" name="updatenotifier_security">
    <exp>Sunt actualizări de securitate.</exp>
  </expression>
  <expression id="plugin_updatenotifier_005" name="updatenotifier_no">
    <exp>Nu actualizări disponibile</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/bat/lang/de.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: de.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: German Created by: Matthias Freund (MAFLO321)
  -->
<tns:translationPlugin language="german" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_bat_001" name="bat_title">
    <exp>Akku-Status</exp>
  </expression>
  <expression id="plugin_bat_002" name="bat_date">
    <exp>Letzte Aktualisierung</exp>
  </expression>
  <expression id="plugin_bat_003" name="bat_design_capacity">
    <exp>Bemeskapazität</exp>
  </expression>
  <expression id="plugin_bat_004" name="bat_remaining_capacity">
    <exp>Übrige Kapazität</exp>
  </expression>
  <expression id="plugin_bat_005" name="bat_design_voltage">
    <exp>Bemessungsspannung</exp>
  </expression>
  <expression id="plugin_bat_006" name="bat_present_voltage">
    <exp>Momentane Spannung</exp>
  </expression>
  <expression id="plugin_bat_007" name="bat_item">
    <exp>Dinge</exp>
  </expression>
  <expression id="plugin_bat_008" name="bat_value">
    <exp>Werte</exp>
  </expression>
  <expression id="plugin_bat_009" name="bat_charging_state">
    <exp>Ladezustand</exp>
  </expression>
  <expression id="plugin_bat_010" name="bat_battery_type">
    <exp>Akku-Typ</exp>
  </expression>
  <expression id="plugin_bat_011" name="bat_battery_temperature">
    <exp>Akku-Temperatur</exp>
  </expression>
  <expression id="plugin_bat_012" name="bat_battery_condition">
    <exp>Akku-Zustand</exp>
  </expression>
  <expression id="plugin_bat_013" name="bat_cycle_count">
    <exp>Cycle Count</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/ps/lang/uk.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: uk.xml 661 2017-06-03 16:32:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Ukrainian Created by: Rostyslav Gaitkulov (nightfly)
  -->
<tns:translationPlugin language="ukrainian" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_ps_001" name="ps_title">
    <exp>Стан процесів</exp>
  </expression>
  <expression id="plugin_ps_002" name="ps_command">
    <exp>Команда</exp>
  </expression>
  <expression id="plugin_ps_003" name="ps_pid">
    <exp>ID процесу</exp>
  </expression>
  <expression id="plugin_ps_004" name="ps_ppid">
    <exp>ID батьківський</exp>
  </expression>
  <expression id="plugin_ps_005" name="ps_mem">
    <exp>Використано пам`яті</exp>
  </expression>
  <expression id="plugin_ps_006" name="ps_cpu">
    <exp>CPU Usage</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/raid/lang/cz.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: cz.xml 661 2012-08-27 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Czech Created by: Tomáš Růžička
  -->
<tns:translationPlugin language="czech" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_raid_001" name="raid_title">
    <exp>Stav RAIDu</exp>
  </expression>
  <expression id="plugin_raid_002" name="raid_infos">
    <exp>Dodatečné informace </exp>
  </expression>
  <expression id="plugin_raid_003" name="raid_name">
    <exp>Name</exp>
  </expression>
  <expression id="plugin_raid_004" name="raid_status">
    <exp>Stav</exp>
  </expression>
  <expression id="plugin_raid_005" name="raid_level">
    <exp>Úroveň RAIDu</exp>
  </expression>
  <expression id="plugin_raid_006" name="raid_size">
    <exp>Size</exp>
  </expression>
  <expression id="plugin_raid_007" name="raid_stride">
    <exp>Stride</exp>
  </expression>
  <expression id="plugin_raid_008" name="raid_subsets">
    <exp>Subsets</exp>
  </expression>
  <expression id="plugin_raid_009" name="raid_devs">
    <exp>Devices</exp>
  </expression>
  <expression id="plugin_raid_010" name="raid_spares">
    <exp>Spares</exp>
  </expression>
  <expression id="plugin_raid_011" name="raid_curact">
    <exp>Current Action</exp>
  </expression>
  <expression id="plugin_raid_012" name="raid_finish">
    <exp>Čas dokončení</exp>
  </expression>
  <expression id="plugin_raid_013" name="raid_chunk">
    <exp>Velikost proužku</exp>
  </expression>
  <expression id="plugin_raid_014" name="raid_algo">
    <exp>Algoritmus</exp>
  </expression>
  <expression id="plugin_raid_015" name="raid_superb">
    <exp>Persistentní Superblock</exp>
  </expression>
  <expression id="plugin_raid_016" name="raid_avail">
    <exp>dostupný</exp>
  </expression>
  <expression id="plugin_raid_017" name="raids_navail">
    <exp>nedostupný</exp>
  </expression>
  <expression id="plugin_raid_018" name="raid_regact">
    <exp>Registrovné/aktivní disky</exp>
  </expression>
  <expression id="plugin_raid_019" name="raid_controller">
    <exp>Controller</exp>
  </expression>
  <expression id="plugin_raid_020" name="raid_battcond">
    <exp>Battery Condition</exp>
  </expression>
  <expression id="plugin_raid_021" name="raid_supported">
    <exp>Poodporované typy RAID</exp>
  </expression>
  <expression id="plugin_raid_022" name="raid_program">
    <exp>Program</exp>
  </expression>
  <expression id="plugin_raid_023" name="raid_readpolicy">
    <exp>Read Policy</exp>
  </expression>
  <expression id="plugin_raid_024" name="raid_writepolicy">
    <exp>Write Policy</exp>
  </expression>
  <expression id="plugin_raid_025" name="raid_cachesize">
    <exp>Cache Size</exp>
  </expression>
  <expression id="plugin_raid_026" name="raid_badblocks">
    <exp>Bad Blocks</exp>
  </expression>
  <expression id="plugin_raid_027" name="raid_diskcache">
    <exp>Disk Cache</exp>
  </expression>
  <expression id="plugin_raid_028" name="raid_stripe">
    <exp>Stripe Size</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/snmppinfo/lang/fr.xml
<?xml version="1.0" encoding="utf-8"?>
  <!--
    phpSysInfo language file Language: French Created by: phpsysinfo
  -->
<tns:translationPlugin language="french" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_snmppinfo_001" name="snmppinfo_title">
    <exp>Imprimantes</exp>
  </expression>
  <expression id="plugin_snmppinfo_002" name="snmppinfo_date">
    <exp>Dernière actualisation</exp>
  </expression>
  <expression id="plugin_snmppinfo_003" name="snmppinfo_printer">
    <exp>Imprimante</exp>
  </expression>
  <expression id="plugin_snmppinfo_004" name="snmppinfo_percent">
    <exp>Pourcent</exp>
  </expression>
  <expression id="plugin_snmppinfo_005" name="snmppinfo_units">
    <exp>Unité</exp>
  </expression>
  <expression id="plugin_snmppinfo_006" name="snmppinfo_enough">
    <exp>suffisamment</exp>
  </expression>
  <expression id="plugin_snmppinfo_007" name="snmppinfo_unknown">
    <exp>inconnu</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/dmraid/lang/ru.xml
<?xml version="1.0" encoding="utf-8"?>
  <!--
    phpSysInfo language file Language: Russian Created by: Denis Sevostyanov (den007)
  -->
<tns:translationPlugin language="english" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_dmraid_001" name="dmraid_title">
    <exp>RAID Статус</exp>
  </expression>
  <expression id="plugin_dmraid_002" name="dmraid_devices">
    <exp>RAID-Устройств</exp>
  </expression>
  <expression id="plugin_dmraid_003" name="dmraid_infos">
    <exp>Дополнительная Информация</exp>
  </expression>
  <expression id="plugin_dmraid_004" name="dmraid_name">
    <exp>Имя</exp>
  </expression>
  <expression id="plugin_dmraid_005" name="dmraid_status">
    <exp>Статус</exp>
  </expression>
  <expression id="plugin_dmraid_006" name="dmraid_type">
    <exp>RAID-Тип</exp>
  </expression>
  <expression id="plugin_dmraid_007" name="dmraid_size">
    <exp>Размер</exp>
  </expression>
  <expression id="plugin_dmraid_008" name="dmraid_stride">
    <exp>Шаг</exp>
  </expression>
  <expression id="plugin_dmraid_009" name="dmraid_subsets">
    <exp>Подмножество</exp>
  </expression>
  <expression id="plugin_dmraid_010" name="dmraid_devs">
    <exp>Устройство</exp>
  </expression>
  <expression id="plugin_dmraid_011" name="dmraid_spares">
    <exp>Резервировано</exp>
  </expression>
</tns:translationPlugin>

=== sentora/sentora-core/etc/apps/phpsysinfo/plugins/dmraid/lang/ro.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- $Id: ro.xml 661 2014-05-02 11:26:39Z namiltd $ -->
  <!--
    phpSysInfo language file Language: Romană Created by: Iulian Alexe
  -->
<tns:translationPlugin language="romana" charset="utf-8"
  xmlns:tns="http://phpsysinfo.sourceforge.net/translation-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://phpsysinfo.sourceforge.net/translation-plugin ../../../language/translation-plugin.xsd">
  <expression id="plugin_dmraid_001" name="dmraid_title">
    <exp>Stare RAID</exp>
  </expression>
  <expression id="plugin_dmraid_002" name="dmraid_devices">
    <exp>Dispozitive RAID</exp>
  </expression>
  <expression id="plugin_dmraid_003" name="dmraid_infos">
    <exp>Informații Aditionale </exp>
  </expression>
  <expression id="plugin_dmraid_004" name="dmraid_name">
    <exp>Nume</exp>
  </expression>
  <expression id="plugin_dmraid_005" name="dmraid_status">
    <exp>Stare</exp>
  </expression>
  <expression id="plugin_dmraid_006" name="dmraid_type">
    <exp>Tip RAID</exp>
  </expression>
  <expression id="plugin_dmraid_007" name="dmraid_size">
    <exp>Dimensiune</exp>
  </expression>
  <expression id="plugin_dmraid_008" name="dmraid_stride">
    <exp>Pas</exp>
  </expression>
  <expression id="plugin_dmraid_009" name="dmraid_subsets">
    <exp>Subseturi</exp>
  </expression>
  <expression id="plugin_dmraid_010" name="dmraid_devs">
    <exp>Dispozitive</exp>
  </expression>
  <expression id="plugin_dmraid_011" name="dmraid_spares">
    <exp>Piese</exp>
  </expression>
</tns:translationPlugin>
